name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - portaudio
  - ffmpeg
  - pip:
    - openai
    - python-dotenv
    - SpeechRecognition
    - pydub
    - keyboard
    - pygame==2.6.1